---
title: "photometa"
output: html_document
date: "2023-08-28"
---

## Install packages and load libraries
```{r, echo=FALSE}
# install.packages("magick")
library(magick)
library(tidyverse)
library(lubridate)
library(dplyr)
library(data.table)
library(hrbrthemes)
library(viridis)
library(magrittr)
library(data.table)
```

## Load taxa lists
```{r, echo=FALSE}
# specify the directory where the files are located
dir_path <- "~/enriquemontes01@gmail.com - Google Drive/My Drive/GDrive/OCED_AOML/WS_cruises/plankton_imaging/CPICS/TS.Master_selection/"

# obtain a list of file names in the directory
file_names <- list.files(path = dir_path, pattern = ".txt", full.names = TRUE)

# loop over each file and import the tables (use this for DATES)
for (file in file_names) {
  table_name <- gsub(".txt", "", basename(file)) # get the name of the table from the file name
  assign(table_name, read.table(file = file, header = FALSE, sep = "\t") %>%
           mutate(date = as.POSIXct(substr(V1, start = 24, stop = 38), format="%Y%m%d_%H%M%S", tz="UTC")))
}
```

## Extract metada from images for individual taxa lists
```{r, echo=FALSE}
# # PNG image
# image_path <- "~/Desktop/20230305_050036.630.0.png"
# 
# # Load the PNG image
# image <- image_read(image_path)
# 
# # Get metadata
# metadata1 <- image_info(image)
# print(metadata1)

# Set path directory
path_to_files <- "~/Desktop/cpics_img/"
setwd(path_to_files)

# 'filename_list' is a data frame with a column named 'img_file_name'
filename_list <- class.Decapods %>% rename(img_file_name = V1)

# Initialize a list to store metadata
metadata_list <- list()

# Iterate through each row in 'filename_list'
for (row in 1:nrow(filename_list)) {
  filename <- filename_list[row, "img_file_name"]
  
  # Construct the full path to the image file in directory
  full_path <- file.path(path_to_files, filename)
  
  # Check if the file exists
  if (file.exists(full_path)) {
    # Read metadata using image_read function from magick
    img <- image_read(full_path)
    metadata <- image_info(img)
    
    # Append metadata to the list
    metadata_list[[row]] <- c(filename = filename, metadata)
  } else {
    cat("File not found:", full_path, "\n")
  }
}

# Convert the list of metadata to a data frame
metadata_df <- do.call(rbind, metadata_list)

# Print the resulting metadata data frame
print(metadata_df)
```


## Extract metada from images looping through all taxa lists
```{r, echo=FALSE}
# Set path directory
path_to_files <- "~/Desktop/cpics_img/"
setwd(path_to_files)

# Directory for selected images
selected_dir <- file.path(path_to_files, "selected")
if (!dir.exists(selected_dir)) {
  dir.create(selected_dir)
}

# List of data frames
data_frame_names <- ls(pattern = "^class\\.")  # Get all data frames starting with "class."

# Initialize a list to store metadata
metadata_list <- list()

# Loop through each data frame
for (df_name in data_frame_names) {
  # Get the data frame using the name
  current_df <- get(df_name)
  
  # Rename filename column if needed
  current_df <- current_df %>% rename(img_file_name = V1)
  
  # Get the data frame name without the "class." prefix
  df_name_without_prefix <- sub("^class\\.", "", df_name)
  
  # Iterate through each row in the data frame
  for (row in 1:nrow(current_df)) {
    filename <- current_df[row, "img_file_name"]
    
    # Construct the full path to the image file in directory
    full_path <- file.path(path_to_files, filename)
    
    # Check if the file exists
    if (file.exists(full_path)) {
      # Read metadata using image_read function from magick
      img <- image_read(full_path)
      metadata <- image_info(img)
      
      # Append metadata to the list along with data frame name
      metadata_list[[length(metadata_list) + 1]] <- c(filename = filename, 
                                                     data_frame = df_name_without_prefix,
                                                     metadata)
      # Copy the image to the 'selected' directory
      selected_path <- file.path(selected_dir, basename(filename))
      file.copy(full_path, selected_path)
    } else {
      cat("File not found:", full_path, "\n")
    }
  }
}

# Combine metadata from all data frames into a single data frame
metadata_df_all <- bind_rows(metadata_list)

```

## Match images to cruise data with a single taxon list
```{r}
# Directory where the CTD metadata is located
dir_path2 <- "~/enriquemontes01@gmail.com - Google Drive/My Drive/GDrive/OCED_AOML/WS_cruises/plankton_imaging/CPICS/ws_cruise_ctd/"
file_name <- list.files(path = dir_path2, pattern = "ctd_meta_v2.csv", full.names = TRUE)
ctd_meta <- read.csv(file_name, fill = TRUE) %>%
  mutate(GMT.datetime = as.POSIXct(GMT.datetime, format="%Y%m%d_%H%M", tz="UTC"))

# Convert data frames to data.tables
class_dt <- as.data.table(class.Decapods) %>% rename(datetime = date)
class_dt <- class_dt %>% rename(img_file_name = V1)

# Initialize an empty list to store results
result_list <- list()

# Iterate over each row in class_dt
for (i in seq_len(nrow(class_dt))) {
  # Find the index of the closest datetime in ctd_meta
  closest_index <- which.min(abs(ctd_meta$GMT.datetime - class_dt$datetime[i]))
  
  # Extract corresponding data from ctd_meta
  result <- data.table(
    img_file_name = class_dt$img_file_name[i],
    object_id = substr(class_dt$img_file_name[i], start = 24, stop = 44),
    object_speciesID = "decapoda",
    object_date = gsub("-", "", as.Date(class_dt$datetime[i])),
    object_time = format(class_dt$datetime[i], format = "%H%M%S"),
    cruiseID = ctd_meta$cruiseID[closest_index],
    ctd_date = gsub("-", "", as.Date(ctd_meta$GMT.datetime[closest_index])),
    ctd_time = format(ctd_meta$GMT.datetime[closest_index], format = "%H%M%S"),
    station = ctd_meta$Station[closest_index],
    object_lat = ctd_meta$dec_lat[closest_index],
    object_lon = ctd_meta$dec_lon[closest_index],
    object_depth_min = 0,
    object_depth_max = ctd_meta$depth_max[closest_index],
    temp_degC = ctd_meta$temp..degC.[closest_index],
    salinity = ctd_meta$salinity[closest_index],
    chl_a = ctd_meta$Avg.chl.a..ug.L.[closest_index],
    do = ctd_meta$DO..mg.L.[closest_index],
    nitrate = ctd_meta$NO3....uM.[closest_index],
    phosphate = ctd_meta$PO4...uM.[closest_index],
    silicate = ctd_meta$Si.....uM.[closest_index],
    seascape.8day = ctd_meta$X8.day.seascapes[closest_index],
    seascape.monthly = ctd_meta$monthly.seascapes[closest_index]
  )
  
  # Append the result to the result list
  result_list[[i]] <- result
}

# Combine all results into a single data table
final_table <- rbindlist(result_list)

# Print the final table
print(final_table)

```


## Match images to cruise data with all taxa lists
```{r, echo=FALSE}
# Directory where the CTD metadata is located
dir_path2 <- "~/enriquemontes01@gmail.com - Google Drive/My Drive/GDrive/OCED_AOML/WS_cruises/plankton_imaging/CPICS/ws_cruise_ctd/"
file_name <- list.files(path = dir_path2, pattern = "ctd_meta_v2.csv", full.names = TRUE)
ctd_meta <- read.csv(file_name, fill = TRUE) %>%
  mutate(GMT.datetime = as.POSIXct(GMT.datetime, format="%Y%m%d_%H%M", tz="UTC"))

# List of data frame names
data_frame_names <- ls(pattern = "^class\\.")

# Initialize an empty list to store results
result_list <- list()

# Iterate over each data frame
for (df_name in data_frame_names) {
  # Get the data frame using the name
  current_df <- get(df_name)
  
  # Rename columns if needed
  current_df <- current_df %>% rename(datetime = date, img_file_name = V1)
  
  # Extract the species ID from data_frame_name
  object_speciesID <- sub("^class\\.", "", df_name)
  
  # Iterate over each row in the data frame
  for (i in seq_len(nrow(current_df))) {
    # Find the index of the closest datetime in ctd_meta
    closest_index <- which.min(abs(ctd_meta$GMT.datetime - current_df$datetime[i]))
    
    # Extract corresponding data from ctd_meta
    result <- data.table(
      img_file_name = current_df$img_file_name[i],
      object_id = substr(current_df$img_file_name[i], start = 24, stop = 44),
      object_speciesID = object_speciesID,  # Use the extracted object_speciesID
      object_date = gsub("-", "", as.Date(current_df$datetime[i])),
      object_time = format(current_df$datetime[i], format = "%H%M%S"),
      cruiseID = ctd_meta$cruiseID[closest_index],
      ctd_date = gsub("-", "", as.Date(ctd_meta$GMT.datetime[closest_index])),
      ctd_time = format(ctd_meta$GMT.datetime[closest_index], format = "%H%M%S"),
      station = ctd_meta$Station[closest_index],
      object_lat = ctd_meta$dec_lat[closest_index],
      object_lon = ctd_meta$dec_lon[closest_index],
      object_depth_min = 0,
      object_depth_max = ctd_meta$depth_max[closest_index],
      temp_degC = ctd_meta$temp..degC.[closest_index],
      salinity = ctd_meta$salinity[closest_index],
      chl_a = ctd_meta$Avg.chl.a..ug.L.[closest_index],
      do = ctd_meta$DO..mg.L.[closest_index],
      nitrate = ctd_meta$NO3....uM.[closest_index],
      phosphate = ctd_meta$PO4...uM.[closest_index],
      silicate = ctd_meta$Si.....uM.[closest_index],
      seascape.8day = ctd_meta$X8.day.seascapes[closest_index],
      seascape.monthly = ctd_meta$monthly.seascapes[closest_index]
    )
    
    # Append the result to the result list
    result_list[[length(result_list) + 1]] <- result
  }
}

# Combine all results into a single data table
final_table_all <- rbindlist(result_list)

```


## Merge cruise data and image metadata
```{r, echo=FALSE}
# Append selected columns to dfB
df_merged <- cbind(final_table_all, metadata_df_all) %>%
  mutate(across(everything(), as.character))
# select columns for Ecotaxa table
df_merged_sel <- df_merged[, c("img_file_name", 
                               "object_id", 
                               "object_date",
                               "object_time",
                               "cruiseID",
                               "ctd_date",
                               "ctd_time",
                               "station",
                               "object_lat",
                               "object_lon",
                               "object_depth_min",
                               "object_depth_max",
                               "format",
                               "width",
                               "height",
                               "colorspace",
                               "matte",
                               "filesize",
                               "density"
                               )]

# Export table
# - add data format codes; [f] for floats, [t] for text
format_codes <- as.data.frame(matrix(c("t", "t", "t", "t", "t", "t", "t", "t", "f", "f", "f", "f", "t", "f", "f", "t", "t", "f", "f"), nrow = 1)) 
colnames(format_codes) <- colnames(df_merged_sel)
ecotaxa_table <- rbind(format_codes, df_merged_sel)

# replace column names as needed
colnames(ecotaxa_table)[which(names(ecotaxa_table) == "colorspace")] <- "color_space"
colnames(ecotaxa_table)[which(names(ecotaxa_table) == "filesize")] <- "file_size"

# Print the resulting data frame
print(ecotaxa_table)

# write.csv(df_merged, , row.names=FALSE)
write.table(ecotaxa_table,"~/Desktop/ecotaxa_sfer-mbon.txt",sep="\t",row.names=FALSE)

# DONE
```

# Generate plots 
```{r}
library(tidyverse)
library(hrbrthemes)
library(viridis)

# set RGB values for the plots
r_vals <- round(c(0, 0, 0, 0.125, 0.375, 1, 1) * 255, 0)
g_vals <- round(c(0, 0.375, 0.875, 1, 1, 0.875, 0.125) * 255, 0)
b_vals <- round(c(0.875, 1, 1, 0.875, 0.625, 0, 0) * 255, 0)
custom_pal <- cbind(r_vals, g_vals, b_vals)
custom_pal_hex <- rgb(custom_pal[, 1], custom_pal[, 2], custom_pal[, 3], maxColorValue=255)
# pal_final <- c(custom_pal_hex[3], custom_pal_hex[4], custom_pal_hex[5], )

# filter out rows with NA values in column seascapes
df_filtered <- ctd_meta[complete.cases(ctd_meta$X8.day.seascapes),]

# Convert the 'x' column to character
df_filtered$X8.day.seascapes <- as.character(df_filtered$X8.day.seascapes)

# Variables
# Avg.chl.a..ug.L.
# salinity
# NH4...uM.
# NO3.NO2..uM.
# DO..mg.L.
# temp..degC.

# Plot
# See https://cran.r-project.org/web/packages/viridis/vignettes/intro-to-viridis.html for color palette options
pp <- df_filtered %>%
  ggplot( aes(x=X8.day.seascapes, y=salinity, fill=X8.day.seascapes)) +
    geom_boxplot() +
    # scale_fill_viridis(option="H", discrete = TRUE, alpha=0.6) +
    scale_fill_manual(values = custom_pal_hex) +
    geom_jitter(color="black", size=0.8, alpha=0.9) +
    labs(x = "Seascape class") +
    # labs(y = expression("[Chl-a] (mg/L)")) +
    labs(y = expression("Salinity")) +
    # labs(y = expression(paste("Temperature (", degree, "C) at 1 m depth"))) +
    # labs(y = expression("DO (mg/L)")) +
    # labs(y = expression("NO"["x"] ~ mu*"M")) +
    # theme(axis.title.y = element_text(hjust = 1))
    # scale_x_discrete(labels= c("Tropical/Subtropical Upwelling", 
    #                          "Tropical Seas", 
    #                          "Warm, Blooms, High Nuts", 
    #                          "Tropical/Subtropical Transition", 
    #                          "Temperate Transition")) +
    theme_ipsum() +
    theme(
      legend.position="none",
      plot.title = element_text(size=11)
    ) +
    # ggtitle("A boxplot with jitter") +
    # theme(axis.text.x = element_text(angle = 45)) +
  ylim(28, 37) +  
  theme(axis.text.x = element_text(size = 32),  # Set X-axis label font size
          axis.text.y = element_text(size = 32)) +
    theme(axis.title.x = element_text(size = 18),
          axis.title.y = element_text(size = 18)) +
    theme(legend.text = element_text(size = 32)) 
pp
```